export enum EMetatransactionActionType {
  BUY_PACK = "BUY_PACK",
  UNBOX_PACK = "UNBOX_PACK",
  CREATE_LISTING = "CREATE_LISTING",
  FULFILL_LISTING = "FULFILL_LISTING",
  DELETE_LISTINGS = "DELETE_LISTINGS",
  CLAIM_PRIZE = "CLAIM_PRIZE",
  TRADE_EXPIRED_PIECES = "TRADE_EXPIRED_PIECES",
  TRANSFER_PIECE = "TRANSFER_PIECE",
}
